-- The pveproxy certificate's SANs cover the hostname (pve1 / pve1.pnuops.com)
-- and the campus IP, NOT the vmbr1 bridge IP 172.30.0.1 — so with CA pinning
-- the client must address the API by a SAN name. LXC 101 maps pve1 to
-- 172.30.0.1 in /etc/hosts (set up when the application container is built).
-- Found at the cutover smoke (2026-07-09): step 3 failed hostname
-- verification against https://172.30.0.1:8006 (V3 seed value).
-- The correction itself is gone: it existed to repair a node row a migration
-- had seeded, and no migration seeds a node any longer. An operator bootstrap
-- script registers the node, and it refuses an api_host that is not a SAN of
-- the certificate the api pins — which is the rule this file discovered, now
-- enforced where the row is actually written instead of patched afterwards.
