-- New explicit policies are adopted by an administrator, never by migration.
alter table users add column row_revision bigint not null default 0;
comment on column users.row_revision is '동시 계정 변경이 역할과 토큰 버전을 덮어쓰지 않도록 보호하는 행 버전';
alter table orgs add column admin_revision bigint not null default 0;
alter table orgs add column request_mail_mode varchar(24);
alter table orgs add constraint orgs_request_mail_mode_check
    check (request_mail_mode in ('ALL_APPROVERS', 'DESIGNATED'));
comment on column orgs.admin_revision is '기관 역할 명단과 신청 메일 수신 설정의 변경 버전';
comment on column orgs.request_mail_mode is '명시 수신 방식. NULL은 아직 전환하지 않은 기존 수신 규칙';

alter table audit_logs add column target_org_id bigint references orgs(id);
alter table audit_logs add column target_org_name text;
create index audit_logs_target_org_created_idx on audit_logs(target_org_id, created_at desc, id desc)
    where target_org_id is not null;
comment on column audit_logs.target_org_id is '행위자의 기관과 별도로 기록한 변경 대상 기관';
comment on column audit_logs.target_org_name is '감사 기록 당시 변경 대상 기관 이름';

create table request_notification_selections (
    id bigint generated by default as identity primary key,
    request_id bigint not null unique references requests(id),
    org_id bigint not null references orgs(id),
    policy_revision bigint not null,
    mail_mode varchar(24) not null check (mail_mode in ('LEGACY', 'ALL_APPROVERS', 'DESIGNATED')),
    recipients jsonb not null,
    created_at timestamptz not null default now()
);
comment on table request_notification_selections is '신청 접수 당시 수신자와 제외 이유. 현재 기관 명단으로 다시 계산하지 않음';
comment on column request_notification_selections.recipients is '접수 당시 기관 역할, 계정 상태, 명단과 메일 주소 및 채널별 선정 결과';

alter table notifications add column request_selection_id bigint references request_notification_selections(id);
alter table notifications add column recipient_email text;
alter table notifications add column skip_reason text;
comment on column notifications.recipient_email is '큐 등록 시 확정한 메일 주소. NULL인 과거 기록은 당시 주소 미상';
comment on column notifications.skip_reason is '메일을 보내지 않은 사유';
