-- Delivery evidence outlives the console inbox; no environment or policy data is inserted.
alter type notification_status add value if not exists 'SENDING';
alter type notification_status add value if not exists 'UNKNOWN';
alter table notifications add column delivery_claim_id uuid;
alter table notifications add column delivery_claimed_at timestamptz;

create table mail_deliveries (
    id bigint generated by default as identity primary key,
    public_id uuid not null unique default gen_random_uuid(),
    source_kind text not null check (source_kind in ('NOTIFICATION', 'ACCOUNT')),
    notification_id bigint unique references notifications(id) on delete set null,
    notification_public_id uuid unique,
    recipient_user_id uuid,
    recipient_email text,
    event text not null,
    title text not null,
    link_path text,
    request_id uuid,
    org_id uuid,
    announcement_id uuid,
    policy_revision bigint,
    mail_mode text,
    state text not null check (state in ('PENDING', 'SENDING', 'SENT', 'FAILED', 'SKIPPED', 'UNKNOWN')),
    attempts integer not null default 0,
    failure_code text,
    next_attempt_at timestamptz,
    sent_at timestamptz,
    bundle boolean not null default false,
    claim_id uuid,
    claimed_at timestamptz,
    expires_at timestamptz,
    created_at timestamptz not null default now()
);
create index mail_deliveries_created_idx on mail_deliveries(created_at desc, id desc);
create index mail_deliveries_request_idx on mail_deliveries(request_id, created_at desc) where request_id is not null;
create index mail_deliveries_announcement_idx on mail_deliveries(announcement_id, created_at desc) where announcement_id is not null;
create index mail_deliveries_org_idx on mail_deliveries(org_id, created_at desc) where org_id is not null;
create index mail_deliveries_state_created_idx on mail_deliveries(state, created_at desc);
comment on table mail_deliveries is '영구 발송 증거. 인증 토큰, 본문과 인증 링크는 저장하지 않음';
comment on column mail_deliveries.recipient_email is '큐 등록 당시 또는 실제 시도한 주소. NULL인 과거 발송의 주소는 미상';
comment on column mail_deliveries.notification_public_id is '알림함 항목이 정리된 뒤에도 유지하는 원본 알림 식별자';
comment on column mail_deliveries.claim_id is '현재 발송 시도의 소유자. 수신자 재선정에는 사용하지 않음';

create table mail_delivery_attempts (
    id bigint generated by default as identity primary key,
    delivery_id bigint not null references mail_deliveries(id),
    attempt_no integer not null,
    dispatch_id uuid not null,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    outcome text not null check (outcome in ('STARTED', 'SENT', 'FAILED', 'UNKNOWN')),
    failure_code text,
    unique (delivery_id, attempt_no)
);
create index mail_delivery_attempts_dispatch_idx on mail_delivery_attempts(dispatch_id);
comment on table mail_delivery_attempts is 'SMTP 시도별 영구 결과. SENT는 SMTP 인계이며 최종 메일함 도착 증거가 아님';
