-- Terminology standardization (2026-07-16): this migration renamed the
-- admin-delete notice key to the vm_* prefix every other VM setting uses, and
-- restated two Korean descriptions in the standardized terms.
--
-- Nothing is left to do. All three statements read and wrote settings rows that
-- no migration creates any more: the values and their descriptions are
-- deployment content an operator bootstrap script writes, so a rename or a
-- relabel applied here would find nothing and the current text is written once,
-- correctly, by whoever creates the row. The key this one renamed is itself gone
-- (V54); it took four migrations across this file's history to seed, relabel,
-- rename and finally delete one setting that the product no longer has, which is
-- the clearest argument there is for keeping deployment content out of the
-- schema. The file stays so the version sequence keeps no holes.
