-- 점검 모드·공지 배너·문의처 (계약 v0.9.0 GET /meta/status).
--
-- This migration once seeded maintenance_mode, maintenance_message,
-- banner_message and contact_email. It no longer does: a maintenance notice, a
-- banner and an operations contact address are deployment content, not schema,
-- and the address in particular is a real mailbox that only the deployment knows.
-- An operator bootstrap script writes the four rows; the dev/test seeder supplies
-- equivalents. Every reader falls back cleanly when a row is absent — the
-- switch reads false and the three strings read as unset (null in responses),
-- which is the same state the empty-string seed used to express.
