-- 웹 터미널 전역 킬 스위치 (계약 v0.10.0, 내부 웹 터미널 계약).
--
-- This migration once seeded web_terminal_enabled = false. It no longer does:
-- whether the browser terminal's infrastructure is wired and safe to serve is a
-- fact about a deployment rather than schema, exactly as with the SSH gateway
-- switch. An operator bootstrap script writes the row; the dev/test seeder
-- supplies an equivalent. Sessions and tickets are in memory, so with the row
-- gone this migration adds nothing at all. Ticket issue and re-exchange are
-- refused while the switch is absent or false, and a session already running ends
-- at the next 60-second re-validation.
