-- Display-wording fix: this migration renamed the terms/privacy titles (and the
-- matching heading inside each body) to the official product name, updating the
-- v1 rows in place so existing consents stayed valid and no re-consent gate
-- fired.
--
-- Nothing is left to do. The documents it rewrote were seeded by V41, which no
-- longer publishes them: the wording of a legal document is deployment content
-- rather than schema, so an operator bootstrap script publishes it and any later
-- correction is made to the published text, not through a migration. Three
-- migrations existed for one document -- one to seed it and two to fix its title
-- -- which is exactly the cost this removal is paying off. The file stays so the
-- version sequence keeps no holes.
