-- Display-wording fix, the second half of the change V51 started: prefix the
-- official product name to the privacy-policy title as well.
--
-- Nothing is left to do, for the same reason as V51. The document it rewrote is
-- no longer published by a migration; an operator bootstrap script publishes the
-- text and corrects it there. The file stays so the version sequence keeps no
-- holes.
