-- Reserved/profanity subdomain expansion (2026-07-28 operator decision): this
-- migration replaced both lists with a survey of campus labels, network and
-- protocol names, platform self-protection entries, generic service and
-- environment names, and a profanity/impersonation top-up.
--
-- Nothing is left to do. Which names a deployment refuses to hand out is an
-- operator judgement about that deployment, not schema -- the lists are
-- admin-editable at runtime for the same reason -- so an operator bootstrap
-- script writes them and extends them there. Rewriting a value here would also
-- have silently discarded whatever an operator had since added through the admin
-- screen. Development and test get a short representative list from the
-- dev/test seeder. The file stays so the version sequence keeps no holes.
