-- Security-review follow-up to the V55 expansion (2026-07-28 independent review
-- of self-service publishing): this migration added campus authentication and
-- identity service names, generic authentication labels, the bare university
-- tokens and the obvious composites of already-reserved names, because with the
-- approval gate gone the reserved list is the squatting defense.
--
-- Nothing is left to do, for the same reason as V55: the list is operator
-- judgement written by an operator bootstrap script and extended through the
-- admin screen, not schema. The reasoning behind the list is worth keeping even
-- though the statement is gone -- reserved matching stays exact, because
-- word-level matching would block legitimate compounds such as my-blog. The file
-- stays so the version sequence keeps no holes.
