-- The IP quarantine window is coupled to the forwarding relay's snapshot
-- replay: a relay agent re-applies its persisted snapshot on boot for as long as
-- that snapshot is considered usable (24 hours), so a released address must stay
-- unassignable at least that long. Below it, the address could be reassigned
-- while stale forwarding rules still point at it and public traffic would land
-- on a different tenant's VM.
--
-- The floor itself lives in the settings editor, which refuses anything under
-- 24, and that is where it is enforced. This migration only restated the
-- setting's Korean description to say why, and there is no longer a row to
-- restate: the value and its description are deployment content an operator
-- bootstrap script writes, with the current wording written once at creation.
-- The file stays so the version sequence keeps no holes.
